import { useTranslation } from 'react-i18next';
import type { ExportTableTypes } from '@/types/ExportHistoryTypes';
import clip1 from '@/assets/images/clip1.webp';
import clip2 from '@/assets/images/clip2.webp';
import clip3 from '@/assets/images/clip3.webp';
import clip4 from '@/assets/images/clip4.webp';
import clip5 from '@/assets/images/clip5.webp';
import clip6 from '@/assets/images/clip6.webp';
import clip7 from '@/assets/images/clip7.webp';
import clip8 from '@/assets/images/clip8.webp';
import clip9 from '@/assets/images/clip9.webp';
import clip10 from '@/assets/images/clip10.webp';

export function exportTableData(): ExportTableTypes[] {
  const { t } = useTranslation();

  return [
    {
      id: 'CLIP-1287',
      thumbnail: clip1,
      title: t('clips-title.clip1-title'),
      duration: '0:58',
      project: t('overview.project-title-1'),
      format: 'mp4',
      resolution: '1080×1920',
      aspectRatio: '9:16',
      exportedAt: new Date(),
      time: '10:24 AM',
      size: '45.2 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-1286',
      thumbnail: clip2,
      title: t('clips-title.clip2-title'),
      duration: '0:45',
      project: t('overview.project-title-1'),
      format: 'mp4',
      resolution: '1080×1920',
      aspectRatio: '9:16',
      exportedAt: new Date(),
      time: '10:20 AM',
      size: '32.7 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-1285',
      thumbnail: clip3,
      title: t('clips-title.clip3-title'),
      duration: '01:02',
      project: t('overview.project-title-1'),
      format: 'mov',
      resolution: '1920×1080',
      aspectRatio: '16:9',
      exportedAt: new Date(),
      time: '4:25 PM',
      size: '85.6 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-1284',
      thumbnail: clip4,
      title: t('clips-title.clip4-title'),
      duration: '00:50',
      project: t('overview.project-title-1'),
      format: 'mp4',
      resolution: '1080×1080',
      aspectRatio: '1:1',
      exportedAt: new Date(),
      time: '4:40 PM',
      size: '28.4 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-1281',
      thumbnail: clip7,
      title: t('clips-title.clip7-title'),
      duration: '00:44',
      project: t('overview.project-title-1'),
      format: 'mp4',
      resolution: '1080×1920',
      aspectRatio: '9:16',
      exportedAt: new Date(),
      time: '11:20 AM',
      size: '30.2 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-1020',
      thumbnail: clip9,
      title: t('clips-title.clip12-title'),
      duration: '00:44',
      project: t('overview.project-title-3'),
      format: 'mp4',
      resolution: '1080×1920',
      aspectRatio: '9:16',
      exportedAt: new Date(),
      time: '2:15 PM',
      size: '26.1 MB',
      status: 'processing',
    },
    {
      id: 'CLIP-0987',
      thumbnail: clip10,
      title: t('clips-title.clip13-title'),
      duration: '01:15',
      project: t('overview.project-title-5'),
      format: 'mp4',
      resolution: '1920×1080',
      aspectRatio: '16:9',
      exportedAt: new Date(),
      time: '11:30 AM',
      size: '60.3 MB',
      status: 'failed',
    },
    {
      id: 'CLIP-0985',
      thumbnail: clip5,
      title: t('clips-title.clip5-title'),
      duration: '0:47',
      project: t('overview.project-title-1'),
      format: 'mp4',
      resolution: '1080×1920',
      aspectRatio: '9:16',
      exportedAt: new Date(),
      time: '9:12 AM',
      size: '29.8 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-0979',
      thumbnail: clip6,
      title: t('clips-title.clip6-title'),
      duration: '0:39',
      project: t('overview.project-title-1'),
      format: 'mov',
      resolution: '1080×1080',
      aspectRatio: '1:1',
      exportedAt: new Date(),
      time: '7:40 AM',
      size: '41.7 MB',
      status: 'completed',
    },
    {
      id: 'CLIP-0974',
      thumbnail: clip8,
      title: t('clips-title.clip8-title'),
      duration: '0:41',
      project: t('overview.project-title-1'),
      format: 'mp4',
      resolution: '1080×1920',
      aspectRatio: '9:16',
      exportedAt: new Date(),
      time: '3:55 PM',
      size: '36.9 MB',
      status: 'completed',
    },
  ];
}
