import type { Icon } from '@phosphor-icons/react';
import {
  HouseIcon,
  FolderPlusIcon,
  CropIcon,
  ChartBarIcon,
  SquaresFourIcon,
  FirstAidKitIcon,
  UploadIcon,
  GearIcon,
  CaretDownIcon,
  PlusIcon,
  BellIcon,
  VideoCameraIcon,
  ClockIcon,
  ArrowSquareOutIcon,
  EyeIcon,
  CheckIcon,
  SpinnerGapIcon,
  DotsThreeVerticalIcon,
  MagnifyingGlassIcon,
  CaretLeftIcon,
  CaretRightIcon,
  ArrowLeftIcon,
  HeartIcon,
  ShareFatIcon,
  DownloadSimpleIcon,
  PencilSimpleIcon,
  CalendarBlankIcon,
  InfoIcon,
  QuestionIcon,
  UsersThreeIcon,
  DeviceMobileIcon,
  FileIcon,
  XIcon,
  ArrowsClockwiseIcon,
  DotsThreeIcon,
  UserIcon,
  CalendarCheckIcon,
  HardDrivesIcon,
  ShieldCheckIcon,
  MoneyIcon,
  CameraIcon,
  GlobeStandIcon,
  GlobeIcon,
  SunIcon,
  SunDimIcon,
  TableIcon,
  CloudArrowUpIcon,
  TrashIcon,
  CrownSimpleIcon,
  InfinityIcon,
  HighDefinitionIcon,
  FloppyDiskIcon,
  BoxArrowDownIcon,
  SealCheckIcon,
  SphereIcon,
  SparkleIcon,
  MonitorIcon,
  FrameCornersIcon,
  CodesandboxLogoIcon,
  PulseIcon,
  CassetteTapeIcon,
  SlidersIcon,
  CardholderIcon,
  FileTextIcon,
  FolderOpenIcon,
  ArrowRightIcon,
  LightbulbIcon,
  FunnelIcon,
  FolderSimpleIcon,
  EnvelopeSimpleIcon,
  NotificationIcon,
  CheckCircleIcon,
  StarIcon,
  MoonIcon,
  WarningIcon,
  MegaphoneIcon,
  WrenchIcon,
  LaptopIcon,
  ShieldCheckeredIcon,
  ChatCenteredDotsIcon,
  ScanIcon,
  CircleIcon,
  FireIcon,
  TrendUpIcon,
  CheckSquareIcon,
  YoutubeLogoIcon,
  InstagramLogoIcon,
  TiktokLogoIcon,
  TwitterLogoIcon,
  WarningCircleIcon,
  TrendDownIcon,
  DesktopIcon,
  DeviceTabletIcon,
  PlayIcon,
  ArrowUpRightIcon,
} from '@phosphor-icons/react';

const icons = {
  HouseIcon,
  FolderPlusIcon,
  CropIcon,
  ChartBarIcon,
  SquaresFourIcon,
  FirstAidKitIcon,
  UploadIcon,
  GearIcon,
  CaretDownIcon,
  PlusIcon,
  BellIcon,
  VideoCameraIcon,
  ClockIcon,
  ArrowSquareOutIcon,
  EyeIcon,
  CheckIcon,
  SpinnerGapIcon,
  DotsThreeVerticalIcon,
  MagnifyingGlassIcon,
  CaretLeftIcon,
  CaretRightIcon,
  ArrowLeftIcon,
  HeartIcon,
  ShareFatIcon,
  DownloadSimpleIcon,
  PencilSimpleIcon,
  CalendarBlankIcon,
  InfoIcon,
  QuestionIcon,
  UsersThreeIcon,
  DeviceMobileIcon,
  FileIcon,
  XIcon,
  ArrowsClockwiseIcon,
  DotsThreeIcon,
  UserIcon,
  CalendarCheckIcon,
  HardDrivesIcon,
  ShieldCheckIcon,
  MoneyIcon,
  CameraIcon,
  GlobeStandIcon,
  GlobeIcon,
  SunIcon,
  SunDimIcon,
  TableIcon,
  CloudArrowUpIcon,
  TrashIcon,
  CrownSimpleIcon,
  InfinityIcon,
  HighDefinitionIcon,
  FloppyDiskIcon,
  BoxArrowDownIcon,
  SealCheckIcon,
  SphereIcon,
  SparkleIcon,
  MonitorIcon,
  FrameCornersIcon,
  CodesandboxLogoIcon,
  PulseIcon,
  CassetteTapeIcon,
  SlidersIcon,
  CardholderIcon,
  FileTextIcon,
  FolderOpenIcon,
  ArrowRightIcon,
  LightbulbIcon,
  FunnelIcon,
  FolderSimpleIcon,
  EnvelopeSimpleIcon,
  NotificationIcon,
  CheckCircleIcon,
  StarIcon,
  MoonIcon,
  WarningIcon,
  MegaphoneIcon,
  WrenchIcon,
  LaptopIcon,
  ShieldCheckeredIcon,
  ChatCenteredDotsIcon,
  ScanIcon,
  CircleIcon,
  FireIcon,
  TrendUpIcon,
  CheckSquareIcon,
  YoutubeLogoIcon,
  InstagramLogoIcon,
  TiktokLogoIcon,
  TwitterLogoIcon,
  WarningCircleIcon,
  TrendDownIcon,
  DesktopIcon,
  DeviceTabletIcon,
  PlayIcon,
  ArrowUpRightIcon,
} satisfies Record<string, Icon>;

export type IconType = keyof typeof icons;

interface ClipIconsProps {
  icon: IconType;
  size?: number | string;
  color?: string;
  weight?: React.ComponentProps<Icon>['weight'];
  className?: string;
}

export function ClipIcons(props: ClipIconsProps) {
  const { icon, size = 24, color, weight = 'regular', className } = props;

  const IconComponent = icons[icon];

  return <IconComponent size={size} color={color} weight={weight} className={className} />;
}
